[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = [
  "node build.cjs",
  "ls -la dist/"
]

[start]
cmd = "cd dist && npm install --production --no-audit && npm start"